name: Samriddha Basu (The Dork Knight Rises)
encoding: UTF-8
markdown: kramdown
paginate: 6
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
url: https://samriddhabasu.github.io
gems:
  - jekyll-sitemap
  - jekyll-paginate
